const ET_RESTO_MENU_LOADED = 'MENU_LOADED';
const ET_RESTO_MENU_STATUS = 'MENU_STATUS';
const ET_RESTO_ITEM_STATUS = 'ITEM_STATUS';
const ET_RESTO_ITEM_LOADED = 'ITEM_LOADED';

export {
    ET_RESTO_MENU_LOADED,
    ET_RESTO_MENU_STATUS,
    ET_RESTO_ITEM_STATUS,
    ET_RESTO_ITEM_LOADED
};