const ET_RESTO_MENU_LOADED = 'MENU_LOADED';
const ET_RESTO_MENU_STATUS = 'MENU_STATUS';
const ET_RESTO_ITEM_STATUS = 'ITEM_STATUS';
const ET_RESTO_ITEM_LOADED = 'ITEM_LOADED';
const ET_RESTO_SELECT_ITEM_ADD = 'SELECT_ITEM_ADD';
const ET_RESTO_SELECT_ITEM_DELETE = 'SELECT_ITEM_DELETE';
const ET_RESTO_SELECT_ITEM_ALL_DELETE = 'SELECT_ITEM_ALL_DELETE';

export {
    ET_RESTO_MENU_LOADED,
    ET_RESTO_MENU_STATUS,
    ET_RESTO_ITEM_STATUS,
    ET_RESTO_ITEM_LOADED,
    ET_RESTO_SELECT_ITEM_ADD,
    ET_RESTO_SELECT_ITEM_DELETE,
    ET_RESTO_SELECT_ITEM_ALL_DELETE
};